/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/src/components/schedule/DaySchedule`; params?: Router.UnknownInputParams; } | { pathname: `/src/components/schedule/LessonCard`; params?: Router.UnknownInputParams; } | { pathname: `/src/constants/colors`; params?: Router.UnknownInputParams; } | { pathname: `/src/constants/scheduleFilters`; params?: Router.UnknownInputParams; } | { pathname: `/src/context/ScheduleContext`; params?: Router.UnknownInputParams; } | { pathname: `/src/navigation/types`; params?: Router.UnknownInputParams; } | { pathname: `/src/screens/MainScreen`; params?: Router.UnknownInputParams; } | { pathname: `/src/screens/SettingsScreen`; params?: Router.UnknownInputParams; } | { pathname: `/src/types/index.d`; params?: Router.UnknownInputParams; } | { pathname: `/src/types/schedule`; params?: Router.UnknownInputParams; } | { pathname: `/src/utils/dateHelpers`; params?: Router.UnknownInputParams; } | { pathname: `/src/utils/storage`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/src/components/schedule/DaySchedule`; params?: Router.UnknownOutputParams; } | { pathname: `/src/components/schedule/LessonCard`; params?: Router.UnknownOutputParams; } | { pathname: `/src/constants/colors`; params?: Router.UnknownOutputParams; } | { pathname: `/src/constants/scheduleFilters`; params?: Router.UnknownOutputParams; } | { pathname: `/src/context/ScheduleContext`; params?: Router.UnknownOutputParams; } | { pathname: `/src/navigation/types`; params?: Router.UnknownOutputParams; } | { pathname: `/src/screens/MainScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/src/screens/SettingsScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/src/types/index.d`; params?: Router.UnknownOutputParams; } | { pathname: `/src/types/schedule`; params?: Router.UnknownOutputParams; } | { pathname: `/src/utils/dateHelpers`; params?: Router.UnknownOutputParams; } | { pathname: `/src/utils/storage`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/src/components/schedule/DaySchedule${`?${string}` | `#${string}` | ''}` | `/src/components/schedule/LessonCard${`?${string}` | `#${string}` | ''}` | `/src/constants/colors${`?${string}` | `#${string}` | ''}` | `/src/constants/scheduleFilters${`?${string}` | `#${string}` | ''}` | `/src/context/ScheduleContext${`?${string}` | `#${string}` | ''}` | `/src/navigation/types${`?${string}` | `#${string}` | ''}` | `/src/screens/MainScreen${`?${string}` | `#${string}` | ''}` | `/src/screens/SettingsScreen${`?${string}` | `#${string}` | ''}` | `/src/types/index.d${`?${string}` | `#${string}` | ''}` | `/src/types/schedule${`?${string}` | `#${string}` | ''}` | `/src/utils/dateHelpers${`?${string}` | `#${string}` | ''}` | `/src/utils/storage${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/src/components/schedule/DaySchedule`; params?: Router.UnknownInputParams; } | { pathname: `/src/components/schedule/LessonCard`; params?: Router.UnknownInputParams; } | { pathname: `/src/constants/colors`; params?: Router.UnknownInputParams; } | { pathname: `/src/constants/scheduleFilters`; params?: Router.UnknownInputParams; } | { pathname: `/src/context/ScheduleContext`; params?: Router.UnknownInputParams; } | { pathname: `/src/navigation/types`; params?: Router.UnknownInputParams; } | { pathname: `/src/screens/MainScreen`; params?: Router.UnknownInputParams; } | { pathname: `/src/screens/SettingsScreen`; params?: Router.UnknownInputParams; } | { pathname: `/src/types/index.d`; params?: Router.UnknownInputParams; } | { pathname: `/src/types/schedule`; params?: Router.UnknownInputParams; } | { pathname: `/src/utils/dateHelpers`; params?: Router.UnknownInputParams; } | { pathname: `/src/utils/storage`; params?: Router.UnknownInputParams; };
    }
  }
}
