/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(stack)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(stack)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/src/components/schedule/DaySchedule`; params?: Router.UnknownInputParams; } | { pathname: `/src/components/schedule/LessonCard`; params?: Router.UnknownInputParams; } | { pathname: `/src/components/settings/ScheduleSelector`; params?: Router.UnknownInputParams; } | { pathname: `/src/components/settings/SettingsCategoryes`; params?: Router.UnknownInputParams; } | { pathname: `/src/components/settings/ThemeToggle`; params?: Router.UnknownInputParams; } | { pathname: `/src/constants/colors`; params?: Router.UnknownInputParams; } | { pathname: `/src/constants/scheduleFilters`; params?: Router.UnknownInputParams; } | { pathname: `/src/context/ScheduleContext`; params?: Router.UnknownInputParams; } | { pathname: `/src/context/ThemeContext`; params?: Router.UnknownInputParams; } | { pathname: `/src/types/index.d`; params?: Router.UnknownInputParams; } | { pathname: `/src/types/schedule`; params?: Router.UnknownInputParams; } | { pathname: `/src/types/scheduleSettings`; params?: Router.UnknownInputParams; } | { pathname: `/src/utils/dateHelpers`; params?: Router.UnknownInputParams; } | { pathname: `/src/utils/storage`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(stack)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(stack)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/src/components/schedule/DaySchedule`; params?: Router.UnknownOutputParams; } | { pathname: `/src/components/schedule/LessonCard`; params?: Router.UnknownOutputParams; } | { pathname: `/src/components/settings/ScheduleSelector`; params?: Router.UnknownOutputParams; } | { pathname: `/src/components/settings/SettingsCategoryes`; params?: Router.UnknownOutputParams; } | { pathname: `/src/components/settings/ThemeToggle`; params?: Router.UnknownOutputParams; } | { pathname: `/src/constants/colors`; params?: Router.UnknownOutputParams; } | { pathname: `/src/constants/scheduleFilters`; params?: Router.UnknownOutputParams; } | { pathname: `/src/context/ScheduleContext`; params?: Router.UnknownOutputParams; } | { pathname: `/src/context/ThemeContext`; params?: Router.UnknownOutputParams; } | { pathname: `/src/types/index.d`; params?: Router.UnknownOutputParams; } | { pathname: `/src/types/schedule`; params?: Router.UnknownOutputParams; } | { pathname: `/src/types/scheduleSettings`; params?: Router.UnknownOutputParams; } | { pathname: `/src/utils/dateHelpers`; params?: Router.UnknownOutputParams; } | { pathname: `/src/utils/storage`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(stack)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(stack)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/src/components/schedule/DaySchedule${`?${string}` | `#${string}` | ''}` | `/src/components/schedule/LessonCard${`?${string}` | `#${string}` | ''}` | `/src/components/settings/ScheduleSelector${`?${string}` | `#${string}` | ''}` | `/src/components/settings/SettingsCategoryes${`?${string}` | `#${string}` | ''}` | `/src/components/settings/ThemeToggle${`?${string}` | `#${string}` | ''}` | `/src/constants/colors${`?${string}` | `#${string}` | ''}` | `/src/constants/scheduleFilters${`?${string}` | `#${string}` | ''}` | `/src/context/ScheduleContext${`?${string}` | `#${string}` | ''}` | `/src/context/ThemeContext${`?${string}` | `#${string}` | ''}` | `/src/types/index.d${`?${string}` | `#${string}` | ''}` | `/src/types/schedule${`?${string}` | `#${string}` | ''}` | `/src/types/scheduleSettings${`?${string}` | `#${string}` | ''}` | `/src/utils/dateHelpers${`?${string}` | `#${string}` | ''}` | `/src/utils/storage${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(stack)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(stack)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/src/components/schedule/DaySchedule`; params?: Router.UnknownInputParams; } | { pathname: `/src/components/schedule/LessonCard`; params?: Router.UnknownInputParams; } | { pathname: `/src/components/settings/ScheduleSelector`; params?: Router.UnknownInputParams; } | { pathname: `/src/components/settings/SettingsCategoryes`; params?: Router.UnknownInputParams; } | { pathname: `/src/components/settings/ThemeToggle`; params?: Router.UnknownInputParams; } | { pathname: `/src/constants/colors`; params?: Router.UnknownInputParams; } | { pathname: `/src/constants/scheduleFilters`; params?: Router.UnknownInputParams; } | { pathname: `/src/context/ScheduleContext`; params?: Router.UnknownInputParams; } | { pathname: `/src/context/ThemeContext`; params?: Router.UnknownInputParams; } | { pathname: `/src/types/index.d`; params?: Router.UnknownInputParams; } | { pathname: `/src/types/schedule`; params?: Router.UnknownInputParams; } | { pathname: `/src/types/scheduleSettings`; params?: Router.UnknownInputParams; } | { pathname: `/src/utils/dateHelpers`; params?: Router.UnknownInputParams; } | { pathname: `/src/utils/storage`; params?: Router.UnknownInputParams; };
    }
  }
}
